### ISSUE TITLE
Publication final preparations

### ISSUE THREAD

**Issue by nfreear** [nfreear/pomodoro-chrome-ext#20]
..

* [x] — Review and updated `build/manifest.js` — author field, etc.
* [x] — Review and update Privacy Policy (#6),
* [x] — Review and update README — intro, "Features", screenshots, logo, images, etc.,
* [x] — Collate demo screenshots,
* [x] — Add "No log entries found" text to `pages/log.html`
* [x] — Log table "stripes"? (#19),
* [x] — License (#3),
* [ ] — Report bug — (#21),
* [x] — Rename/move CSS/JS files (#14),
* [x] — Remove unused CSS (#14),
* [x] — Document ideas!! (#22).

..

**Comment by nfreear** [comment]
Plain-text store listing:

---

• 🔧 ⏱️ The block-list, timer duration and other settings are configurable.
• 🌟 🖋️ Add an icon and optionally a note to each timer session.
• 🔔 🫑 An audible bell helps you track your progress.
• 🏹 🎯 Achieve greater focus!
• 🧠 Designed for and by neurodivergent brains.
• 😎 ♿ Designed with accessibility in mind
• 👷‍♀️‍ 🚧 Under active development.

..
